export const SELECTED = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
];

export const CATEGORIES = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Alternative Rock",
    tags: ["Rock", "2000s", "Alternative"],
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Pop Rock",
    tags: ["Pop", "Rock", "Catchy"],
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Emo Rock",
    tags: ["Emo", "Rock", "Emotional"],
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Alternative Rock",
    tags: ["Grunge", "Alternative", "2000s"],
  },
  {
    id: 5,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Punk Rock",
    tags: ["Punk", "Upbeat", "Youth"],
  },
  {
    id: 6,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Alternative Rock",
    tags: ["Rock", "Anthemic", "2000s"],
  },
  {
    id: 7,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Pop Punk",
    tags: ["Pop Punk", "Rebellious", "Energy"],
  },
  {
    id: 8,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Alternative Rock",
    tags: ["Gritty", "Rock", "2000s"],
  },
  {
    id: 9,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Emo Rock",
    tags: ["Emotional", "Rock", "Guitar"],
  },
  {
    id: 10,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Pop Rock",
    tags: ["Catchy", "Mainstream", "Youthful"],
  },
  {
    id: 11,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Punk Rock",
    tags: ["Bold", "Fast", "Energetic"],
  },
  {
    id: 12,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    musicStyle: "Alternative Rock",
    tags: ["Angsty", "Classic", "2000s"],
  },
];

export const JOBS_PROPS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    musicStyle: "Alternative Rock",
    tags: ["Rock", "Alternative", "Emotional"],
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Linkin Park",
    songName: "Numb",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Mike Shinoda",
    musicStyle: "Nu Metal",
    tags: ["Rock", "Alternative", "Angst"],
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Coldplay",
    songName: "Fix You",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Chris Martin",
    musicStyle: "Alternative Rock",
    tags: ["Emotional", "Rock", "Inspiring"],
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Taylor Swift",
    songName: "Blank Space",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Taylor Swift",
    musicStyle: "Pop",
    tags: ["Pop", "Catchy", "Breakup"],
  },
  {
    id: 5,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Adele",
    songName: "Hello",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Adele",
    musicStyle: "Soul",
    tags: ["Emotional", "Pop", "Ballad"],
  },
  {
    id: 6,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Imagine Dragons",
    songName: "Believer",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Dan Reynolds",
    musicStyle: "Alternative Rock",
    tags: ["Energetic", "Rock", "Inspirational"],
  },
  {
    id: 7,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Maroon 5",
    songName: "Sugar",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Adam Levine",
    musicStyle: "Pop Rock",
    tags: ["Pop", "Catchy", "Romantic"],
  },
  {
    id: 8,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Ed Sheeran",
    songName: "Shape of You",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Ed Sheeran",
    musicStyle: "Pop",
    tags: ["Pop", "Dance", "Romantic"],
  },
  {
    id: 9,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Billie Eilish",
    songName: "Bad Guy",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Billie Eilish",
    musicStyle: "Electropop",
    tags: ["Dark", "Pop", "Edgy"],
  },
  {
    id: 10,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Bruno Mars",
    songName: "Uptown Funk",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Mark Ronson",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },

  {
    id: 11,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Dua Lipa",
    songName: "Don't Start Now",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Dua Lipa",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 12,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Katy Perry",
    songName: "Firework",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Katy Perry",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 13,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "The Weeknd",
    songName: "Blinding Lights",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "The Weeknd",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 14,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Post Malone",
    songName: "Circles",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Post Malone",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 15,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Selena Gomez",
    songName: "Lose You to Love Me",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Selena Gomez",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 16,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Shawn Mendes",
    songName: "Stitches",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Shawn Mendes",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 17,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Rihanna",
    songName: "Diamonds",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Sia",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 18,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Halsey",
    songName: "Without Me",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Halsey",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 19,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Nick Jonas",
    songName: "Jealous",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Nick Jonas",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 20,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Ariana Grande",
    songName: "Thank U, Next",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Ariana Grande",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 21,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Travis Scott",
    songName: "Sicko Mode",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Travis Scott",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 22,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Lil Nas X",
    songName: "Old Town Road",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Lil Nas X",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 23,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Miley Cyrus",
    songName: "Wrecking Ball",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Miley Cyrus",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 24,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Beyoncé",
    songName: "Halo",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Beyoncé",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 25,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Jennifer Lopez",
    songName: "On The Floor",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "RedOne",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 26,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Snoop Dogg",
    songName: "Drop It Like It's Hot",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Pharrell Williams",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 27,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Usher",
    songName: "Yeah!",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Usher",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 28,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Kendrick Lamar",
    songName: "HUMBLE.",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Kendrick Lamar",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 29,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Demi Lovato",
    songName: "Sorry Not Sorry",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Demi Lovato",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
  {
    id: 30,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Niall Horan",
    songName: "Slow Hands",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Niall Horan",
    musicStyle: "Funk",
    tags: ["Funky", "Energetic", "Dance"],
  },
];

export const SAVED_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
];

export const APPLIED_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
];

export const ACTIVE_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
];

export const INACTIVE_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
];
